# This workflow compile and push a docker image for release purposes
name: Java CI and release docker test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - uses: jfrog/setup-jfrog-cli@v1
      env:
        JF_ARTIFACTORY_1: ${{ secrets.HARISH_CLI_GITHUB_ACTIONS }}
    - run: |
        # Ping the server
        jfrog rt ping
    - uses: jfrog/setup-jfrog-cli@v1
      env:
        JF_ARTIFACTORY_1: ${{ secrets.HARISH_CLI_GITHUB_ACTIONS }}
        JFROG_CLI_LOG_LEVEL: DEBUG
    - run: |
        jfrog rt mvnc --global --server-id-resolve=artif --server-id-deploy=artif --repo-resolve-releases=libs-release --repo-resolve-snapshots=libs-snapshot --repo-deploy-releases=libs-release-local --repo-deploy-snapshots=libs-snapshot-local
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-jfrog-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-jfrog-
    - name: Build with Maven
      # skip tests because they are connecting to data sources
      run: jfrog rt mvn -Dmaven.test.skip.exec -B install
      env:
       M2_HOME: /usr/share/apache-maven-3.8.1 # If this is wrong, see output of mvn –version
    - name: Docker build
      run: |
        docker build -t $IMAGE_REPO_NAME --build-arg JAR_FILE=$IMAGE_REPO_NAME/target/$IMAGE_REPO_NAME.jar .
        docker tag $IMAGE_REPO_NAME vigneshs.jfrog.io/docker/$IMAGE_REPO_NAME:${GITHUB_REF##*/}
        jfrog rt dp vigneshs.jfrog.io/$IMAGE_REPO_NAME:${GITHUB_REF##*/} docker
      env:
        JFROG_CLI_LOG_LEVEL: DEBUG
        IMAGE_REPO_NAME: docker
